version: '3.8'

services:
  # 1. BANCO DE DADOS POSTGRESQL
  postgres:
    image: postgres:15
    container_name: ml_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-ecommerce_dw}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. ZOOKEEPER (Gerenciador do Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: ml_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 3. APACHE KAFKA
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: ml_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Cria o tópico automaticamente ao iniciar
      KAFKA_CREATE_TOPICS: "ml_smartphones_raw:1:1"

volumes:
  postgres_data: